"""
Agent Tool Preflight
====================

Shows how to use ``guard_output`` as a pre-flight check before an agent
executes a tool call whose output was generated by an LLM.

The pattern:
  1. The agent plans a tool call and generates the arguments.
  2. Before executing the tool, gate the generated arguments through
     ``guard_output`` with ``TaskCriticality.CRITICAL``.
  3. If the routing action is BLOCK, skip the tool call and log a warning.

This is useful for agents that write code, send emails, or execute
database queries -- any tool where a hallucinated argument could cause
real damage.
"""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass
from pathlib import Path

from hallucination_sentinel.calibration import load_calibration
from hallucination_sentinel.integrations.middleware import (
    PolicyAction,
    RoutingDecision,
    TaskCriticality,
    guard_output,
)


# ---------------------------------------------------------------------------
# Stub tool infrastructure
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ToolCall:
    """A planned tool invocation."""

    name: str
    arguments: str


def plan_tool_call(user_request: str) -> ToolCall:
    """Have the LLM plan a tool call for *user_request*.

    Replace this with your actual agent/LLM call.
    """
    # Simulated: the agent decides to run a SQL query
    return ToolCall(
        name="execute_sql",
        arguments=f"SELECT * FROM users WHERE name = '{user_request}'",
    )


def execute_tool(tool_call: ToolCall) -> str:
    """Execute *tool_call* and return the result.

    Replace this with your actual tool dispatcher.
    """
    return f"[tool result for {tool_call.name}: {tool_call.arguments}]"


# ---------------------------------------------------------------------------
# Preflight gate
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class PreflightResult:
    """Outcome of the pre-flight check."""

    tool_call: ToolCall
    decision: RoutingDecision
    executed: bool
    result: Optional[str] = None
    blocked_reason: Optional[str] = None


def agent_tool_preflight(
    user_request: str,
    calibration_path: str,
) -> PreflightResult:
    """Plan a tool call and gate it before execution.

    Args:
        user_request: The user's natural-language request.
        calibration_path: Path to a calibration artifact JSON file.

    Returns:
        A :class:`PreflightResult` describing what happened.
    """
    calibration = load_calibration(calibration_path)

    # 1. Plan the tool call
    tool_call = plan_tool_call(user_request)

    # 2. Gate the generated arguments
    #    We use CRITICAL policy because tool calls can have side effects.
    decision = guard_output(
        user_request,
        tool_call.arguments,
        calibration=calibration,
        provider="openai",
        policy=TaskCriticality.CRITICAL,
    )

    # 3. Act on the decision
    if decision.action is PolicyAction.BLOCK:
        return PreflightResult(
            tool_call=tool_call,
            decision=decision,
            executed=False,
            blocked_reason=(
                "Tool call blocked: CES score indicates high hallucination risk "
                "in the generated arguments.  Review the diagnostic_peaks for "
                "regions of uncertainty."
            ),
        )

    if decision.action is PolicyAction.HUMAN_REVIEW:
        return PreflightResult(
            tool_call=tool_call,
            decision=decision,
            executed=False,
            blocked_reason=(
                "Tool call requires human review before execution. "
                f"CES score: {decision.ces_score:.4f}, "
                f"risk level: {decision.risk_level.value}."
            ),
        )

    # ALLOW / WARN / REQUIRE_EVIDENCE => execute (WARN logs but proceeds)
    result = execute_tool(tool_call)
    return PreflightResult(
        tool_call=tool_call,
        decision=decision,
        executed=True,
        result=result,
    )


# ---------------------------------------------------------------------------
# CLI demo
# ---------------------------------------------------------------------------


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python agent_tool_preflight.py <calibration.json>")
        print()
        print("Demonstrates agent tool-call preflight gating.")
        sys.exit(1)

    calibration_path = sys.argv[1]
    request = "Find all users with the name Alice"

    result = agent_tool_preflight(request, calibration_path)

    output = {
        "tool_call": {
            "name": result.tool_call.name,
            "arguments": result.tool_call.arguments,
        },
        "executed": result.executed,
        "result": result.result,
        "blocked_reason": result.blocked_reason,
        "decision": result.decision.to_dict(),
    }
    print(json.dumps(output, indent=2))


if __name__ == "__main__":
    main()
